Add files via upload
sviridov6012/Laba1Sviridov pull request #1
Opened 2024-10-19 20:06 UTC by sviridov6012

![image](https://github.com/user-attachments/assets/e97e555d-3d91-4fb4-bda7-ae97a17cbb46)

2024-10-20 09:07 UTC, rmushkin requested changes
Пожалуйста, поправьте файлы. Будут вопросы - пишите!

2024-10-20 09:07 UTC, rmushkin commented on Лабораторная работа 1/Task_1.py
> +len = len(numbers)
Попробуйте чуть ниже в коде продублировать эти строчки и запустить. Убедитесь, что всё сломалось :)
Написав
`sum = sum(...)`, вы переобозначили `sum` и тем самым потеряли доступ ко встроенной функции `sum` (то же и с `len`). Не надо так делать.

2024-10-20 09:07 UTC, rmushkin commented on Лабораторная работа 1/Task_1.py
> +cen = sum/len
`cen` - плохое имя для переменной согласно PEP8](https://peps.python.org/pep-0008/) (указаниям по стилю написания кода). Не понятно, что это значит. Используйте полные английские слова без сокращений (кроме общепринятых или необходимых).

2024-10-20 09:07 UTC, rmushkin commented on Лабораторная работа 1/Task_2.py
> +val = int(vol//book)
[PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода): вокруг математических операторов должны быть пробелы.

2024-10-22 22:03 UTC, rmushkin requested changes
Пожалуйста, исправьте пару мелочей и дайте мне доступ на запись в репозиторий, чтобы я мог принять и закрыть.

2024-10-22 22:03 UTC, rmushkin commented on Лабораторная работа 1/Task_1.py
> +sum1 = sum(numbers[:4] + numbers[5:])
[PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода): `sum1` - плохое имя. `sum_1` лучше, `sum_of_numbers` ещё лучше.

2024-10-22 22:03 UTC, rmushkin commented on Лабораторная работа 1/Task_1.py
> +middle = sum1/length
[PEP8](https://peps.python.org/pep-0008/): вокруг математических операторов нужны пробелы

2024-10-24 08:23 UTC, rmushkin approved these changes
Принято ✅

2024-10-24 08:26 UTC, merged

2024-10-24 08:51 UTC, sviridov6012 commented
уже пригласил в коллабораторов

чт, 24 окт. 2024 г., 11:24 rmushkin ***@***.***>:

> ***@***.**** approved this pull request.
>
> Принято ✅
> Теперь, пожалуйста, пригласите
> <https://docs.github.com/ru/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository>
> меня в коллабораторы, чтобы я мог закрыть пулл-реквест.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sviridov6012/Laba1Sviridov/pull/1#pullrequestreview-2391696997>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGFJA6L25Z4FAY7KDNJUCZLZ5CVCNAVCNFSM6AAAAABQHY7II6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOJRGY4TMOJZG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>